apiVersion: v1
kind: Service
metadata:
  labels:
    app: streamlit
  name: streamlit
spec:
  ports:
  - name: "8051"
    nodePort: 30000
    port: 8051
    protocol: TCP
    targetPort: 8051
  selector:
    app: streamlit
  type: NodePort
status:
  loadBalancer: {}
